name = input("Enter Name: ")
address = input("Enter Address: ")
email = input("Enter Email: ")
phone = input("Enter Phone Number: ")

print("--- Person Details ---")
print("Name:", name)
print("Address:", address)
print("Email:", email)
print("Phone Number:", phone)
